# Adding an account to Rejestr_Kont
POST http://127.0.0.1:5000/api/accounts
Content-Type: application/json

{
    "name": "Jan",
    "surname": "Kowalski",
    "pesel": "12345678901"
}

###
# Getting the number of accounts in Rejestr_Kont
GET http://127.0.0.1:5000/api/accounts/count

###
# Getting account by pesel (account exists)
GET http://127.0.0.1:5000/api/accounts/12345678901

###
# Getting account by pesel (account doesn't exist)
GET http://127.0.0.1:5000/api/accounts/12345678902

###
# Updating an account (account exists)
PATCH http://127.0.0.1:5000/api/accounts/12345678901
Content-Type: application/json

{
    "name": "Janina",
    "saldo": 1000
}


###
# Deleting an account by pesel (account exists)
DELETE http://127.0.0.1:5000/api/accounts/12345678901

###
# Deleting an account by pesel (account doesn't exist)
DELETE http://127.0.0.1:5000/api/accounts/12345678902

###
# Sending a transfer request (account exists)
POST http://127.0.0.1:5000/api/accounts/12345678901/transfer
Content-Type: application/json

{
  "amount": 500,
  "type": "outgoing"
}

###
# Sending a transfer request (account doesn't exist)
POST http://127.0.0.1:5000/api/accounts/12345678902/transfer
Content-Type: application/json

{
  "amount": 500,
  "type": "incoming"
}

###
# Testing the Ministerstwo NIP API - valid NIP
GET https://wl-api.mf.gov.pl/api/search/nip/8461627563?date=2023-12-01

###
# Testing the Ministerstwo NIP API - invalid NIP
GET https://wl-api.mf.gov.pl/api/search/nip/8461627500?date=2023-12-01